name: harvest-news-daily

on:
  schedule:
    # 08:00 ICT = 01:00 UTC
    - cron: '0 1 * * *'
    # 12:00 ICT = 05:00 UTC
    - cron: '0 5 * * *'
    # 15:00 ICT = 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Số ngày gần đây để lấy (mặc định 30)'
        required: false
        default: '30'
      max_pages:
        description: 'Số trang/listsite mỗi nguồn (mặc định 8)'
        required: false
        default: '8'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # để commit file data/ về repo
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run harvester
        env:
          DAYS: ${{ github.event.inputs.days }}
          MAX_PAGES: ${{ github.event.inputs.max_pages }}
        run: |
          # đặt giá trị mặc định khi run theo schedule
          DAYS="${DAYS:-30}"
          MAX_PAGES="${MAX_PAGES:-8}"
          python harvest.py --days "$DAYS" --max-pages "$MAX_PAGES"

